#!/usr/bin/env bash

set -eu
set -o pipefail

FLAGS=(--safe --without-K)

function main {
    find script/.. -name '*.agdai' -exec rm {} \;
    pushd script/../src
    time agda "${FLAGS[@]}" Everything.agda
    popd
    exit 0
}

main
