#!/usr/bin/env bash

set -eu
set -o pipefail

FLAGS=(--safe --without-K)
SRC='script/../src'

function main {
    pushd "${SRC}"
    find . -name '*.agdai' -exec rm {} \;
    time agda "${FLAGS[@]}" Everything.agda
    popd
    exit 0
}

main
