#!/usr/bin/env bash

set -eu
set -o pipefail

FLAGS=(--safe --without-K)
SRC='script/../src'

function main {
    find "${SRC}" -name '*.agdai' -exec rm {} \;
    pushd "${SRC}"
    time agda "${FLAGS[@]}" Everything.agda
    popd
    exit 0
}

main
